Add cli
JetBrains-Research/dataset-anonymizer pull request #6
Opened 2020-11-23 14:02 UTC by nbirillo

Note: I changed the `IntelliJ` plugin version (0.4.22 -> 0.4.21) because I could not fix a problem: the arguments in the `runIde` task are unavailable in 0.4.22 on my mac, but it works well in Ubuntu. Sorry, I will fix it in the next PR and upgrade the `IntelliJ` plugin version  again

2020-11-24 11:41 UTC, elena-lyulina requested changes

2020-11-24 11:41 UTC, elena-lyulina commented on README.md
> +The plugin deletes all comments in the code snapshots and anonymizes all variables, functions and so on names in the code.
so on -> any other

2020-11-24 11:41 UTC, elena-lyulina commented on README.md
> +To build a .zip distribution of the plugin to run `./gradlew build shadowJar`. The .zip is located in `build/distributions/dataset-anonymizer-1.0-SNAPSHOT.zip`.
to run -> run

2020-11-24 11:41 UTC, elena-lyulina commented on src/main/kotlin/org/jetbrains/research/ml/dataset/anonymizer/Runner.kt
> +            logger.error(ex)
maybe we can combine these blocks?

2020-11-24 11:41 UTC, elena-lyulina commented on src/test/kotlin/org/jetbrains/research/ml/dataset/anonymizer/util/AnonymizerTest.kt
> +        TestCase.assertEquals(expectedDf.toString(), actualDf.toString())
Maybe something with indices?

2020-11-24 12:30 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/dataset/anonymizer/util/AnonymizerTest.kt
> +        TestCase.assertEquals(expectedDf.toString(), actualDf.toString())
no(

2020-11-27 01:30 UTC, elena-lyulina approved these changes
Great!

2020-11-27 01:30 UTC, merged